//project images
import mimo from './mimo.png';
import bopdiagram from './shearbopdiagram.png';

//Project Pages
import CricketAntenna from './pages/CricketAntenna.jsx';
import GpsTracker from './pages/GpsTracker.jsx';
import ShearCalculator from './pages/ShearCalculator.jsx';
import PythonReport from './pages/PythonReport.jsx';
import Kaleidoscope from './pages/Kaleidoscope.jsx';
import JobCompare from './pages/JobCompare.jsx';
import ClimateSensor from './pages/ClimateSensor.jsx';

export const projectlist = [
  {
    path: "projects/gps-tracker",
    element: <GpsTracker/>,
    title: "GPS Tracking Site",
    description: "tracks my RV as I travel.  It utilizes an arduino GPS module, React site and PHP backend",
    tags: ["Arduino", "React"]
  },
  {
    path: "projects/cellantenna",
    element: <CricketAntenna/>,
    title: "Cell Antenna",
    description: "a mobile directional cellular/wifi antenna providing internet connection utilizing a 12V source",
    tags: ["Design"],
    imgsrc: mimo
  },
  {
    path: "projects/shearcalculator",
    element: <ShearCalculator/>,
    title: "Shear Calculator",
    description: "A online PHP/mySQL tool for engineers to evaluate the capabilities of offshore cutting devices and generate reports for clients",
    tags: ["Engineering", "PHP", "mySQL"],
    imgsrc: bopdiagram
  },
  {
      path: "projects/kaleidoscope",
      element: <Kaleidoscope/>,
      title: "Kaleidoscope",
      description: "a present for my wife",
      tags: ["CNC", "3dPrinters", "3dModeling", "Electronics"]
  },
  {
      path: "projects/temphumiditysensor",
      element: <ClimateSensor/>,
      title: "Temp & Humidy Sensor",
      description: "a sensor loggs environment conditions and is graphed on website.",
      tags: ["Arduino", "HTML5", "mySQL", "PHP", "js"]
  },
  {
      path: "projects/pythonreport",
      element: <PythonReport/>,
      title: "Autogenerated Python Reports",
      description: "a Python script that turned inspections logged in excel to hundreds of pdf reports in minutes.",
      tags: ["Python"]
  }, 
  {
    path: "projects/jobcomparer", 
    element: <JobCompare/>,
    title: "Job Comparer Android App",
    description: "Android application that is used to compare job offers and provide a score based on user preferences.  ",
    tags: ["Java", "Android"]
}, 
];
//projects to add:
  //Spare oom bench
  //CNC pull-up bar
  //Android job comparison app
