import React from 'react';
import Container from 'react-bootstrap/Container';
import Carousel from 'react-bootstrap/Carousel';

import pythonreportcmd from './slides/pythonreport/cmd.png';
import report from './slides/pythonreport/report.png';

let caraselTextStyle = {'backgroundColor': "rgba(52, 52, 52, 0.4)",
                    'borderRadius':'5px'};
const PythonReport = (props) => {

    return(
    <Container>
        <h3>Python Report Generator</h3>
        <p>The python report generator was created to quickly create pdf from excel based inspection reports made by field
          surveyors.  The python script took as inputs the excel report in CSV format and inspector data as a json file.  With this information,
          it generated pdf files using the reportlab library.
        </p>

        <p>This was a collaboration between myself and and another.  He did the initial work.  When I took over the project, 
          I put it into version control, created instructions, and moved some of the variables from hard coded lines to user inputs.  
          I maintained this work for 2 yrs after the originator left the company.
        </p>
        <Container className="carouselContainer w-50">
          <Carousel className="">
            <Carousel.Item>
              <img
                className="d-block w-100"
                src={pythonreportcmd}
                alt="Command line"
              />
              <Carousel.Caption>
                <div  style={caraselTextStyle}>
                <h3>python script</h3>
                <p>The executed command line script</p>
                </div>
              </Carousel.Caption>
            </Carousel.Item>
            <Carousel.Item>
              <img
                className="d-block w-100"
                src={report}
                alt="Command line"
              />
              <Carousel.Caption>
                <div  style={caraselTextStyle}>
                <h3>Report</h3>
                <p>An autogenerated report created by the Python Report Generator</p>
                </div>
              </Carousel.Caption>
            </Carousel.Item>
          </Carousel>
        </Container>
        <p><a href="https://github.com/thedavidhanks/5YM-certs-generator" target="_blank"  rel="noopener noreferrer">git repository</a>  
        </p>
    </Container>
    );
};

export default PythonReport;